notifications:
  email:
    on_success: never
    on_failure: change
language: node_js
sudo: false
node_js:
  - 6
  - 7
  - 8
  - "stable"
install:
  - npm install
script:
  - npm test
after_success: npm run coverage
